#define FOPEN_SYSCALL 0x1
#define FCLOSE_SYSCALL 0x2
#define FREAD_SYSCALL 0x3
#define FWRITE_SYSCALL 0x4
#define FSIZE_SYSCALL 0x5

#define EXIT_PROCESS_SYSCALL 0x8
#define EXIT_THREAD_SYSCALL 0x9
#define CREATE_THREAD_SYSCALL 0xA
#define CREATE_PROCESS_SYSCALL 0xB

#define PRINT_SYSCALL 0x10
#define SCAN_SYSCALL 0x11
#define SCAN_LINE_SYSCALL 0x12