DISK_IMAGE = disk_image.img
EFI_PART_SIZE = 64MiB
LOOPN = loop100
MOUNT = /mnt/partition1
MYAPP_EFI = /home/ahmed-farag/src/edk2/Build/MyApp/DEBUG_GCC/X64/MyApp.efi
OVMF_CODE = /home/ahmed-farag/src/edk2/Build/OvmfX64/DEBUG_GCC/FV/OVMF_CODE.fd
OVMF_VARS = /home/ahmed-farag/src/edk2/Build/OvmfX64/DEBUG_GCC/FV/OVMF_VARS.fd
BOOT = BOOTX64.EFI


all: clean run


$(DISK_IMAGE):
	dd if=/dev/zero of=$@ bs=1M count=1024

$(LOOPN): $(DISK_IMAGE)
	sudo losetup /dev/$(LOOPN) $(DISK_IMAGE)

partition: $(LOOPN)
	sudo parted /dev/$(LOOPN) --script mklabel gpt
	sudo parted /dev/$(LOOPN) --script mkpart primary fat32 1MiB $(EFI_PART_SIZE)
	sudo parted /dev/$(LOOPN) --script set 1 boot on
	sudo parted /dev/$(LOOPN) --script mkpart primary $(EFI_PART_SIZE) 100%
	
format: partition
	sudo mkfs.fat -F32 /dev/$(LOOPN)p1

mount: format
	sudo mkdir -p $(MOUNT)
	sudo mount /dev/$(LOOPN)p1 $(MOUNT)

filesystem:
	$(MAKE) -C user

copy: mount filesystem
	cp $(MYAPP_EFI) $(BOOT)
	sudo mkdir -p $(MOUNT)/EFI/BOOT
	sudo cp $(BOOT) $(MOUNT)/EFI/BOOT/
	sudo cp kernel/kernel.o $(MOUNT)/
	sudo dd if=user/filesystem of=/dev/$(LOOPN)p2
	sudo umount $(MOUNT)
	sudo rmdir $(MOUNT)
	sudo losetup -d /dev/$(LOOPN)

run: copy
	sudo qemu-system-x86_64 \
	-monitor stdio \
    -drive format=raw,file=$(DISK_IMAGE) \
    -pflash $(OVMF_CODE) \
    -pflash $(OVMF_VARS) \
    -m 2048M \
	-smp 4 \
    -net none

clean:
	sudo umount $(MOUNT) || true
	sudo rmdir $(MOUNT) || true
	sudo losetup -d /dev/$(LOOPN) || true
	rm -fr $(DISK_IMAGE)
	rm -fr $(BOOT)
