#define FOPEN_SYSCALL 0x1
#define FSIZE_SYSCALL 0x2
#define FCLOSE_SYSCALL 0x3
#define FREAD_SYSCALL 0x4
#define FWRITE_SYSCALL 0x5
#define FCREATE_SYSCALL 0x6
#define FDELETE_SYSCALL 0x7
#define FLIST_SYSCALL 0x8


#define CREATE_PROCESS_SYSCALL 0xA
#define CREATE_THREAD_SYSCALL 0xB
#define EXIT_PROCESS_SYSCALL 0xC
#define EXIT_THREAD_SYSCALL 0xD
#define TERMINATE_PROCESS_SYSCALL 0xE
#define TERMINATE_THREAD_SYSCALL 0xF

#define PRINT_SYSCALL 0x10
#define SCAN_SYSCALL 0x11

#define MEMORY_INIT_INT 0x14

#define EVENT_REG_INT 0x16
#define EVENT_WAIT_INT 0x17

#define NUM_SYSCALL 0x18