#define SCHEDULE_INT 0x40
#define PROCESS_WAITING_INT 0x41
#define THREAD_WAITING_INT 0x42
#define PROCESS_TERMINATED_INT 0x43
#define THREAD_TERMINATED_INT 0x44

#define RESOURCE_REQUEST_INT 10
#define RESOURCE_FREE_INT 11
